# Generated by Django 4.1.3 on 2023-03-14 14:19

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('room', models.CharField(default='room1', max_length=10)),
                ('index', models.CharField(default='1-1', max_length=10)),
                ('status', models.CharField(default='working', max_length=10)),
                ('description', models.CharField(default='default description', max_length=500)),
                ('last_fix_date', models.DateField(default=datetime.datetime)),
            ],
            options={
                'verbose_name': 'my_server',
                'verbose_name_plural': 'my_server',
                'db_table': 'server',
            },
        ),
    ]
